// WARNING: This file has automatically been generated on Sat, 05 Oct 2019 17:36:41 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../../../lib/include/roc/address.h"
#include "../../../lib/include/roc/config.h"
#include "../../../lib/include/roc/context.h"
#include "../../../lib/include/roc/frame.h"
#include "../../../lib/include/roc/log.h"
#include "../../../lib/include/roc/platform.h"
#include "../../../lib/include/roc/receiver.h"
#include "../../../lib/include/roc/sender.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// roc_log_handler_9e4bbc5e is a proxy for callback roc_log_handler.
void roc_log_handler_9e4bbc5e(roc_log_level level, char* component, char* message);

