// WARNING: This file has automatically been generated on Sat, 05 Oct 2019 17:36:41 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package roc provides Go bindings for libroc
*/
package roc
