// WARNING: This file has automatically been generated on Sat, 05 Oct 2019 17:36:41 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package roc

/*
#cgo linux CFLAGS: -I"../../../lib/include"
#cgo linux LDFLAGS: -L"../../../build/x86_64-pc-redhat-linux/gcc-9.1.1-release" -lroc
#include "../../../lib/include/roc/address.h"
#include "../../../lib/include/roc/config.h"
#include "../../../lib/include/roc/context.h"
#include "../../../lib/include/roc/frame.h"
#include "../../../lib/include/roc/log.h"
#include "../../../lib/include/roc/platform.h"
#include "../../../lib/include/roc/receiver.h"
#include "../../../lib/include/roc/sender.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Address as declared in roc/address.h:59
type Address struct {
	ref94efe9d7    *C.roc_address
	allocs94efe9d7 interface{}
}

// ContextConfig as declared in roc/config.h:147
type ContextConfig struct {
	MaxPacketSize  uint32
	MaxFrameSize   uint32
	ref6685576b    *C.roc_context_config
	allocs6685576b interface{}
}

// SenderConfig as declared in roc/config.h:234
type SenderConfig struct {
	FrameSampleRate       uint32
	FrameChannels         ChannelSet
	FrameEncoding         FrameEncoding
	PacketSampleRate      uint32
	PacketChannels        ChannelSet
	PacketEncoding        PacketEncoding
	PacketLength          uint64
	PacketInterleaving    uint32
	AutomaticTiming       uint32
	ResamplerProfile      ResamplerProfile
	FecCode               FecCode
	FecBlockSourcePackets uint32
	FecBlockRepairPackets uint32
	refc92542a4           *C.roc_sender_config
	allocsc92542a4        interface{}
}

// ReceiverConfig as declared in roc/config.h:316
type ReceiverConfig struct {
	FrameSampleRate         uint32
	FrameChannels           ChannelSet
	FrameEncoding           FrameEncoding
	AutomaticTiming         uint32
	ResamplerProfile        ResamplerProfile
	TargetLatency           uint64
	MaxLatencyOverrun       uint64
	MaxLatencyUnderrun      uint64
	NoPlaybackTimeout       int64
	BrokenPlaybackTimeout   int64
	BreakageDetectionWindow uint64
	ref9cfc9e50             *C.roc_receiver_config
	allocs9cfc9e50          interface{}
}

// Context as declared in roc/context.h:41
type Context C.roc_context

// Frame as declared in roc/frame.h:42
type Frame struct {
	Samples       unsafe.Pointer
	SamplesSize   uint
	ref5cb6a60    *C.roc_frame
	allocs5cb6a60 interface{}
}

// LogHandler type as declared in roc/log.h:64
type LogHandler func(level LogLevel, component string, message string)

// Receiver as declared in roc/receiver.h:117
type Receiver C.roc_receiver

// Sender as declared in roc/sender.h:96
type Sender C.roc_sender
